{% set version = "3.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nlmixr2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nlmixr2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nlmixr2/nlmixr2_{{ version }}.tar.gz
  sha256: caa8d29a60fe5291d83359c81a96c417e20f05f241820b6fa517b58c2c14ea1b

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-crayon
    - r-lotri
    - r-magrittr
    - r-nlmixr2data
    - r-nlmixr2est >=2.1.1
    - r-nlmixr2extra
    - r-nlmixr2plot
    - r-rxode2 >=2.0.10
  run:
    - r-base
    - r-cli
    - r-crayon
    - r-lotri
    - r-magrittr
    - r-nlmixr2data
    - r-nlmixr2est >=2.1.1
    - r-nlmixr2extra
    - r-nlmixr2plot
    - r-rxode2 >=2.0.10

test:
  commands:
    - $R -e "library('nlmixr2')"           # [not win]
    - "\"%R%\" -e \"library('nlmixr2')\""  # [win]

about:
  home: https://nlmixr2.org/
  dev_url: https://github.com/nlmixr2/nlmixr2/
  license: GPL-3.0-or-later
  summary: Fit and compare nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2'
    package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: nlmixr2
# Title: Nonlinear Mixed Effects Models in Population PK/PD
# Version: 2.0.9
# Authors@R: c(person("Matthew","Fidler", role = c("aut", "cre"), email = "matthew.fidler@gmail.com", comment=c(ORCID="0000-0001-8538-6691")), person("Yuan", "Xiong", role = "ctb", email = "yuan.xiong@gmail.com"), person("Rik", "Schoemaker", role = "ctb", email = "rik.schoemaker@occams.com", comment=c(ORCID="0000-0002-7538-3005")), person("Justin", "Wilkins", role = "ctb", email = "justin.wilkins@occams.com", comment=c(ORCID="0000-0002-7099-9396")), person("Wenping", "Wang", role = "ctb", email = "wwang8198@gmail.com"), person("Mirjam","Trame", role = "ctb", email="mirjam.trame@gmail.com"), person("Huijuan", "Xu", role="ctb", email="huijuan.xu.pmx@gmail.com"), person("John", "Harrold", role="ctb", email="john.m.harrold@gmail.com"), person("Bill", "Denney", email="wdenney@humanpredictions.com", role="ctb", comment=c(ORCID="0000-0002-5759-428X")), person("Theodoros", "Papathanasiou",  role="ctb"), person("Teun","Post", role = "ctb", email = "t.post@lapp.nl"), person("Richard", "Hooijmaijers", email = "richardhooijmaijers@gmail.com", role = "ctb"))
# Description: Fit and compare nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2' package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>).
# License: GPL (>= 3)
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Imports: nlmixr2est (>= 2.1.1), nlmixr2extra, rxode2 (>= 2.0.10), lotri, nlmixr2plot, magrittr, crayon, cli
# Depends: nlmixr2data
# Suggests: rmarkdown, knitr, devtools, ggplot2, testthat, n1qn1, withr
# BugReports: https://github.com/nlmixr2/nlmixr2/issues/
# URL: https://nlmixr2.org/, https://github.com/nlmixr2/nlmixr2/
# NeedsCompilation: no
# Packaged: 2023-02-21 01:04:35 UTC; matt
# Author: Matthew Fidler [aut, cre] (<https://orcid.org/0000-0001-8538-6691>), Yuan Xiong [ctb], Rik Schoemaker [ctb] (<https://orcid.org/0000-0002-7538-3005>), Justin Wilkins [ctb] (<https://orcid.org/0000-0002-7099-9396>), Wenping Wang [ctb], Mirjam Trame [ctb], Huijuan Xu [ctb], John Harrold [ctb], Bill Denney [ctb] (<https://orcid.org/0000-0002-5759-428X>), Theodoros Papathanasiou [ctb], Teun Post [ctb], Richard Hooijmaijers [ctb]
# Maintainer: Matthew Fidler <matthew.fidler@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-02-21 04:00:02 UTC
